export const Cities= [
    {id:Math.random(),title:"القاهرة"},
    {id:Math.random(),title:"الجيزة"},
    {id:Math.random(),title:"اسكندرية"},
    {id:Math.random(),title:"مطروح"},
    {id:Math.random(),title:"بنى سويف"}, 
    {id:Math.random(),title:"المنيا"},
    {id:Math.random(),title:"اسيوط"},
    {id:Math.random(),title:"الفيوم"},
    {id:Math.random(),title:"قنا"},
    {id:Math.random(),title:"الاقصر "},
    {id:Math.random(),title:"السويس"},
    {id:Math.random(),title:"الاسماعيلية"},
    {id:Math.random(),title:"البحر الاحمر"},
    {id:Math.random(),title:"البحيرة"},
    {id:Math.random(),title:"سوان"},
    {id:Math.random(),title:"بور سعيد"},
    {id:Math.random(),title:"جنوب سيناء"},
    {id:Math.random(),title:"الدقهلية "},
    {id:Math.random(),title:" دمياط"},
    {id:Math.random(),title:"سوهاج"},
    {id:Math.random(),title:"كفر الشيخ "},
    {id:Math.random(),title:"الشرقية"},
    {id:Math.random(),title:"المنوفية "},
    {id:Math.random(),title:"الغربية"},
    {id:Math.random(),title:"الوادى الجديد"},
   
]